# -*- coding: utf-8 -*-
"""Numpy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18njClVeTF4FY3wsFlIlVIkP8LOazBRFc
"""

import numpy as np

arr = np.array([1,2,3])
arr

# to saw dimensions we need to use ndim
# how many square brackets we put it increases the dimensions of array
# []-> 1 dimensioin , [[]]->two dimenstion , [[[]]]->three dimension
arr.ndim

arr = np.array([[[[[[]]]]]])
arr.ndim
arr.shape

arrang = np.arange(0,10) #arange(start,stop,step)
arrang

arr = np.linspace(0,1,5) #linspace(start,stop,number of values)
arr

arr = np.logspace(1,2,2) #logarthmic scale of array
arr

arr = np.zeros([4,4]) #default it gives float value
arr

arr = np.ones([3,3],dtype=int)
arr

arr = np.full([3,3],9)
arr

arr = np.empty([2,3])
arr

arr = np.random.rand(5) # we have to pass how many random numbers we need
arr #generate random values between 0 and 1

arr = np.random.randn(5)
arr #random numbers based on normal distribution

arr = np.random.randint(0,10,size=(2,3))
arr

"""### **NumPy DataTypes and Typecasting**"""

arr = np.array([12,3])
arr.dtype

arr = np.array([1,2.2,3])
arr.dtype

new_arr = arr.astype(np.int64)
new_arr

arr = np.array(["satya"])
arr

new_arr = arr.astype(np.int64)
new_arr #typecasting error because we can't convert it into integer

arr = np.array([1,2,3])
arr.itemsize

"""## **Array Reshaping**"""

# reshape -> it can change dimensions of a array
arr = np.array([1,2,3,4,5,6])
new_arr = arr.reshape(2,3)
new_arr

new_arr = arr.reshape(3,2)
new_arr

# ravel() is used to convert array into 1D array
r = new_arr.ravel()
r
r[0]=100
r
new_arr
# ravel() can change original array when we try to change ravel() array

# flatten it is also used to covert array into 1D arrya, but it make copy of arrya
# if you can change value of flatten it can't effect on original arrya
flat = new_arr.flatten()
flat
flat[0]=1
flat
# new_arr

"""## **Arthimetic Operations on Arrays**"""

a = np.array([1,2,3,4])
b = np.array([4,3,2,1])

print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a//b)
print(a**b)